server:
  port: 9001

spring:
  application:
    name: eureka-client

eureka:
  instance:
    appname: eureka-client
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
    register-with-eureka: true
    fetch-registry: true
management:
  security:
    enabled: false
#zuul:
#  routes:
#    cloud:
#      path: /zuul/**